#     ______     _                ___      ___                  ______                                    #
#   .' ____ \   / |_            .' ..]   .' ..]               .' ___  |                                   #
#   | (___ \_| `| |-'  ,--.    _| |_    _| |_      ______    / .'   \_|   .--.    _ .--.   .---.          #
#    _.____`.   | |   `'_\ :  '-| |-'  '-| |-'    |______|   | |        / .'`\ \ [ `/'`\] / /__\\         #
#   | \____) |  | |,  // | |,   | |      | |                 \ `.___.'\ | \__. |  | |     | \__.,         #
#   \______.'   \__/  \'-;__/  [___]    [___]                 `.____ .'  '.__.'  [___]     '.__.'   4.5.0 #
#                                                                                                         #
#                                                                               By BarraR3port : [CONFIG] #
#                                                                                                         #
# If you need some help, or you have any suggestion please join in my discord:                            #
# ------------------> https://discord.gg/rgekTwy <------------------                                      #
#                                                                                                         #

# ------------> MYSQL <--------------
mysql:
  enabled: false  #<------------------ On true you will use mysql!
  host: "localhost" #<--------------- The host!
  port: "3306" #<-------------------- The port!
  database: "staffcore" #<----------- The name of the database!
  username: "root" #<---------------- The username of the database!
  password: "" #<-------------------- Leave in blanc if you don't use password!

# ------------> BUNGEECORD <--------------
# For using this, you will need to have enabled the mysql otherwise it won't work and may show up some errors
# This is meant to notify all your StaffMembers about the Ban Alerts, Report Alerts, and so on.
# The Mysql is needed cuz that's where the plugin is going to get all the data like: the reason, the name...
bungeecord:
  enabled: false
  server: "the_current_server" # This is the name of the server!
  server_prefix: " &7[&a%server%&7] "

# ------------> STAFF-CORE <---------
# Global Staff Core configurations
disable_outdated_plugin: true # ON ENABLE IF THE PLUGIN IS OUTDATED, IT WILL AUTOMATIC BE DISABLED.
server_prefix: "&8[&a&lSTAFF CORE&r&8]&r "
staff_prefix: "&8[&3&lSTAFF&r&8]&r "
language: "EN_NA" # There are 3 languages available to use: English (EN_NA), Spanish (ES_CL) and French (FR)

# ------------> STAFF-CORE-WEB <---------
# Here you need to fill some data that will be used in case you link the server with
# the StaffCoreWeb
server_address: "play.staffcore.net" # Here goes your server Address
server_name: "StaffCore" # Here you put the Network Name or Server Name

# ------------> DISCORD <--------------
# If you have a discord and you want to implement webhooks with StaffCore, change it to true.
# There are two different channels that StaffCore handles, the Alerts Channel & Debug Channel.
# In the Alerts Channel, all the alerts will be sent to that channel, like Bans, reports, etc.
# In the Debug Channel, everything that happens in the plugin will be sent to that Channel, for exp:
# If a player change his GameMode, or if a player kills another. (THIS IS STILL IN DEVELOPMENT, MORE STUFF SOON)
# Now, How to implement this?, Easy, just Create a Channel > Edit Channel > Integrations > WebHooks > New WebHook >
# Copy WebHook URL and pasted into each Type.
discord:
  type:
    alerts:
      enabled: false
      name: "[STAFF CORE]"
      name_image_url: "https://www.spigotmc.org/data/resource_icons/82/82324.jpg?1599952786" # You can put null
      name_web_url: "https://github.com/BarraR3port" # You can put null if you don't want to use one
      webhook_url: "THE DISCORD WEBHOOK URL" # Here you put the DiscordWebHook Link
      custom_image: true
      custom_image_url: "https://www.spigotmc.org/data/resource_icons/82/82324.jpg?1599952786"
      color: 0xF456F4 # https://www.htmlcsscolor.com/
    debug:
      enabled: false
      name: "[STAFF CORE]"
      name_image_url: "https://www.spigotmc.org/data/resource_icons/82/82324.jpg?1599952786" # You can put null
      name_web_url: "https://github.com/BarraR3port" # You can put null if you don't want to use one
      webhook_url: "THE DISCORD WEBHOOK URL" # Here you put the DiscordWebHook Link
      custom_image: true
      custom_image_url: "https://www.spigotmc.org/data/resource_icons/82/82324.jpg?1599952786"
      color: 0xFF0000 # https://www.htmlcsscolor.com/
      enabled_debugs:
        commands: true
        player_join: true
        player_leave: true
        chat: true

# ------------> STAFF <--------------
staff:
  fly_invincible: true #<------------ On "true" the players with fly On, will be invincible!
  staffchat:
    enable_use_custom: true
    custom_character: "!"

# ------------> SOUNDS <-------------
# Here is a list of all the sounds available: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Sound.html
sounds: true #<---------------------- On True the plugin will execute some sounds!
custom_sounds:
  staff_items_drop: "ENTITY_SLIME_ATTACK"
  staff_mute_alerts: "BLOCK_NOTE_BLOCK_PLING"
  reports_alerts: "BLOCK_NOTE_BLOCK_PLING"
  muted_try_to_chat: "BLOCK_NOTE_BLOCK_PLING"
  mute_alerts: "BLOCK_NOTE_BLOCK_PLING"
  open_report: "BLOCK_NOTE_BLOCK_PLING"
  close_report: "BLOCK_NOTE_BLOCK_PLING"
  delete_report: "ENTITY_WITHER_BREAK_BLOCK"
  freeze: "BLOCK_BEACON_DEACTIVATE"
  un_freeze: "BLOCK_BEACON_ACTIVATE"
  vanished_join: "BLOCK_BUBBLE_COLUMN_BUBBLE_POP"
  invsee: "BLOCK_CHEST_OPEN"
  invsee_close: "BLOCK_CHEST_CLOSE"
  endersee: "BLOCK_ENDER_CHEST_OPEN"
  endersee_close: "BLOCK_ENDER_CHEST_CLOSE"
  ban_alerts: "BLOCK_NOTE_BLOCK_PLING"
  warn_alerts: "BLOCK_NOTE_BLOCK_PLING"
  close_ban: "BLOCK_NOTE_BLOCK_PLING"
  un_ban: "ENTITY_WITHER_BREAK_BLOCK"
  helpop: "BLOCK_NOTE_BLOCK_PLING"

# ------------> PARTICLES <----------
# Here is a list of all the particles available: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Particle.html
custom_particles:
  freeze_player:
    enabled: true
    particle: "TOTEM"
    count: 5
    number_of_times: 20
    offSetX: 3
    offSetY: 3
    offSetZ: 3
  unfreeze_player:
    enabled: true
    particle: "DRAGON_BREATH"
    count: 5
    number_of_times: 20
    offSetX: 3
    offSetY: 3
    offSetZ: 3
  ban:
    enabled: true
    particle: "TOTEM"
    count: 5
    number_of_times: 20
    offSetX: 3
    offSetY: 3
    offSetZ: 3

# ------------> WARN SYSTEM <----------
warns:
  max_warns: 4 # Max amount of warns that a player can have. (THE MAXIMUM AMOUNT IS 7 AND MIN 3)
  ban_on_exceeded: true # Ban on max warn exceeded.
  expire_after: 30 # Expire the warn after this amount of time.
  expire_after_quantity: "d" # This can be: SECONDS (s) | MINUTES (m) | HOURS (h) | DAYS (d)
  notify: true # Notify warned players when they join that the are warned

# ------------> FREEZE <-----------
freeze:
  set_ice_block: true
  cancel_chat_while_frozen: true

# ------------> WIPE <----------
# Just to remember, when a player gets wiped, it will automatically gets kicked out from the
# server. This happens because there are some data that the plugin needs to work fine, otherwise
# it may causes some bugs, and no one wants that!
# (This data is generated once again when the player joins)
wipe:
  bans: true
  reports: true
  warns: true
  wipe_on_ban: true

# ------------> ALERT OPTIONS <----------
alerts:
  tp_to_them: true # Alert players when someone teleported to them.
  tp_all_msg: true # Alert players that they had teleported to a player (through a /tpall).
  wipe_players: false # Alert all the players that a player has been wiped off.
  mute_player: false # Alert all players that a player has been muted.
  report: true # Alert all players about a new reported player.
  freeze: true # Alert all players about a new frozen player.
  ban: false # Alert all players about a new banned player.
  warn: false # Alert all players about a new waned player.
  fake_join_leave_msg: false # Alert players that a staff member leave the server when they turn on/off vanish.

# ------------> CUSTOM INVENTORIES SETTINGS <----------
inventories:
  time_limit: 128
